title: URLs to remember
description: âœ‚ï¸ğŸ”— These are links I find useful.
logo: /assets/img/logo.png
show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal

permalink: /:slug/

plugins:
  - jekyll-redirect-from

repository: https://github.com/alexdelifer/0xde.ca
